### ISSUE TITLE
Name of Repo

### ISSUE THREAD

**Issue by April6804** [Heynowdonttryit/My-Office-Things#1]
You have two Repos, one that is plural and the other without an s.

Office-Things repo has a GitHub Page Link but it is in the About section of both repos.

In the Office Things repo, the desk lamp file extension is spelled wrong, use jpg. Line 8, 11, 17 have spelling errors for the width.

**Comment by Heynowdonttryit** [comment]
I fixed the spelling errors. As for the reason why there are two repos, I hadn’t figured out that we could add to the one that we had forked. I’ll rename this one.
